apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-java-sample-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-java-sample-webapp
  template:
    metadata:
      labels:
        app: docker-java-sample-webapp
    spec:
      containers:
      - name: docker-java-sample-webappaDocker image name if different
        ports:
        - containerPort: 8080
